### ISSUE TITLE
Don't shorten the description (as much), include ellipsis when you do

### ISSUE THREAD

**Issue by qazmlp** [stevencrader/podcastap#8]
While Mastodon has a relatively low character limit by default, this isn't applied to externally-received posts, so you can show (much) more text there. When you do shorten it, it would be helpful to have an indicator like `[…]` to make it clear the text isn't just cut off.

Longer posts wouldn't be annoying to receive since fediverse software is generally very good at collapsing long posts into a "read more" fadeout automatically. (The current post length is enough to trigger this in the mobile app.)
Mastodon will show media attachments outside of this collapsed section, so no UX breakdown in that regard either.

---

One reason the current limit concerns me is that it cuts off the funding links of a podcast I follow.
(It doesn't have the necessary metadata to display the "FUNDING" profile attachment, as it's hosted on Spotify.)

**Comment by stevencrader** [comment]
I agree that is sucks to have the description truncated. Some podcasts have really long episode descriptions. By default, the Podcast Index returns a truncated description. There is a way to get the full description but it currently isn't used by the `ap.podcastindex.org` bridge. 

If you are interested in seeing the code for the bridge, see https://github.com/Podcastindex-org/pi-activitypub-server

**Comment by qazmlp** [comment]
> If you are interested in seeing the code for the bridge, see https://github.com/Podcastindex-org/pi-activitypub-server

Thank you, I was looking for that but couldn't find it earlier.
I'll file any issues in the appropriate repository from now on 👍

I'll close this and file it over there a bit later when I get around to it.
